export const SUPPORTED_LANGUAGES = [
  { code: "af", label: "Afrikaans", match: "af" },
  { code: "sq", label: "Shqip (Albanian)", match: "sq" },
  { code: "am", label: "አማርኛ (Amharic)", match: "am" },
  { code: "ar", label: "العربية (Arabic)", match: "ar" },
  { code: "hy", label: "Հայերեն (Armenian)", match: "hy" },
  { code: "az", label: "Azərbaycan dili (Azerbaijani)", match: "az" },
  { code: "eu", label: "Euskara (Basque)", match: "eu" },
  { code: "be", label: "Беларуская (Belarusian)", match: "be" },
  { code: "bn", label: "বাংলা (Bengali)", match: "bn" },
  { code: "bs", label: "Bosanski (Bosnian)", match: "bs" },
  { code: "bg", label: "Български (Bulgarian)", match: "bg" },
  { code: "ca", label: "Català (Catalan)", match: "ca" },
  { code: "ceb", label: "Cebuano", match: "ceb" },
  { code: "ny", label: "Chichewa", match: "ny" },
  { code: "zh", label: "中文 (Chinese)", match: "zh" },
  { code: "co", label: "Corsu (Corsican)", match: "co" },
  { code: "hr", label: "Hrvatski (Croatian)", match: "hr" },
  { code: "cs", label: "Čeština (Czech)", match: "cs" },
  { code: "da", label: "Dansk (Danish)", match: "da" },
  { code: "nl", label: "Nederlands (Dutch)", match: "nl" },
  { code: "en", label: "English", match: "en" },
  { code: "eo", label: "Esperanto", match: "eo" },
  { code: "et", label: "Eesti (Estonian)", match: "et" },
  { code: "tl", label: "Filipino", match: "tl" },
  { code: "fi", label: "Suomi (Finnish)", match: "fi" },
  { code: "fr", label: "Français", match: "fr" },
  { code: "fy", label: "Frysk (Frisian)", match: "fy" },
  { code: "gl", label: "Galego (Galician)", match: "gl" },
  { code: "ka", label: "ქართული (Georgian)", match: "ka" },
  { code: "de", label: "Deutsch (German)", match: "de" },
  { code: "el", label: "Ελληνικά (Greek)", match: "el" },
  { code: "gu", label: "ગુજરાતી (Gujarati)", match: "gu" },
  { code: "ht", label: "Kreyòl ayisyen (Haitian Creole)", match: "ht" },
  { code: "ha", label: "Hausa", match: "ha" },
  { code: "haw", label: "ʻŌlelo Hawaiʻi (Hawaiian)", match: "haw" },
  { code: "iw", label: "עברית (Hebrew)", match: "iw" },
  { code: "hi", label: "हिन्दी (Hindi)", match: "hi" },
  { code: "hmn", label: "Hmong", match: "hmn" },
  { code: "hu", label: "Magyar (Hungarian)", match: "hu" },
  { code: "is", label: "Íslenska (Icelandic)", match: "is" },
  { code: "ig", label: "Igbo", match: "ig" },
  { code: "id", label: "Bahasa Indonesia (Indonesian)", match: "id" },
  { code: "ga", label: "Gaeilge (Irish)", match: "ga" },
  { code: "it", label: "Italiano (Italian)", match: "it" },
  { code: "ja", label: "日本語 (Japanese)", match: "ja" },
  { code: "jw", label: "Basa Jawa (Javanese)", match: "jw" },
  { code: "kn", label: "ಕನ್ನಡ (Kannada)", match: "kn" },
  { code: "kk", label: "Қазақ тілі (Kazakh)", match: "kk" },
  { code: "km", label: "ខ្មែរ (Khmer)", match: "km" },
  { code: "rw", label: "Kinyarwanda", match: "rw" },
  { code: "ko", label: "한국어 (Korean)", match: "ko" },
  { code: "ku", label: "Kurdî (Kurdish)", match: "ku" },
  { code: "ky", label: "Кыргызча (Kyrgyz)", match: "ky" },
  { code: "lo", label: "ລາວ (Lao)", match: "lo" },
  { code: "la", label: "Latina (Latin)", match: "la" },
  { code: "lv", label: "Latviešu (Latvian)", match: "lv" },
  { code: "lt", label: "Lietuvių (Lithuanian)", match: "lt" },
  { code: "lb", label: "Lëtzebuergesch (Luxembourgish)", match: "lb" },
  { code: "mk", label: "Македонски (Macedonian)", match: "mk" },
  { code: "mg", label: "Malagasy", match: "mg" },
  { code: "ms", label: "Bahasa Melayu (Malay)", match: "ms" },
  { code: "ml", label: "മലയാളം (Malayalam)", match: "ml" },
  { code: "mt", label: "Malti (Maltese)", match: "mt" },
  { code: "mi", label: "Māori", match: "mi" },
  { code: "mr", label: "मराठी (Marathi)", match: "mr" },
  { code: "mn", label: "Монгол (Mongolian)", match: "mn" },
  { code: "my", label: "မြန်မာစာ (Myanmar)", match: "my" },
  { code: "ne", label: "नेपाली (Nepali)", match: "ne" },
  { code: "no", label: "Norsk (Norwegian)", match: "no" },
  { code: "or", label: "ଓଡ଼ିଆ (Odia)", match: "or" },
  { code: "ps", label: "پښتو (Pashto)", match: "ps" },
  { code: "fa", label: "فارسی (Farsi)", match: "fa" },
  { code: "pl", label: "Polski (Polish)", match: "pl" },
  { code: "pt", label: "Português (Portuguese)", match: "pt" },
  { code: "pa", label: "ਪੰਜਾਬੀ (Punjabi)", match: "pa" },
  { code: "ro", label: "Română (Romanian)", match: "ro" },
  { code: "ru", label: "Русский (Russian)", match: "ru" },
  { code: "sm", label: "Samoan", match: "sm" },
  { code: "gd", label: "Gàidhlig (Scots Gaelic)", match: "gd" },
  { code: "sr", label: "Српски (Serbian)", match: "sr" },
  { code: "st", label: "Sesotho", match: "st" },
  { code: "sn", label: "Shona", match: "sn" },
  { code: "sd", label: "سنڌي (Sindhi)", match: "sd" },
  { code: "si", label: "සිංහල (Sinhala)", match: "si" },
  { code: "sk", label: "Slovenčina (Slovak)", match: "sk" },
  { code: "sl", label: "Slovenščina (Slovenian)", match: "sl" },
  { code: "so", label: "Soomaali (Somali)", match: "so" },
  { code: "es", label: "Español (Spanish)", match: "es" },
  { code: "su", label: "Basa Sunda (Sundanese)", match: "su" },
  { code: "sw", label: "Kiswahili (Swahili)", match: "sw" },
  { code: "sv", label: "Svenska (Swedish)", match: "sv" },
  { code: "tg", label: "Тоҷикӣ (Tajik)", match: "tg" },
  { code: "ta", label: "தமிழ் (Tamil)", match: "ta" },
  { code: "tt", label: "Татар (Tatar)", match: "tt" },
  { code: "te", label: "తెలుగు (Telugu)", match: "te" },
  { code: "th", label: "ไทย (Thai)", match: "th" },
  { code: "tr", label: "Türkçe (Turkish)", match: "tr" },
  { code: "tk", label: "Türkmen (Turkmen)", match: "tk" },
  { code: "uk", label: "Українська (Ukrainian)", match: "uk" },
  { code: "ur", label: "اردو (Urdu)", match: "ur" },
  { code: "ug", label: "Uyghur", match: "ug" },
  { code: "uz", label: "Oʻzbek (Uzbek)", match: "uz" },
  { code: "vi", label: "Tiếng Việt (Vietnamese)", match: "vi" },
  { code: "cy", label: "Cymraeg (Welsh)", match: "cy" },
  { code: "xh", label: "isiXhosa (Xhosa)", match: "xh" },
  { code: "yi", label: "ייִדיש (Yiddish)", match: "yi" },
  { code: "yo", label: "Yorùbá", match: "yo" },
  { code: "zu", label: "isiZulu (Zulu)", match: "zu" }
];
